backend:
  name: github
  repo: DxdHaiwan/sandeep-portfolio
  branch: main
  auth_type: implicit

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "content"
    label: "Website Content"
    delete: false
    editor:
      preview: false
    files:
      - name: "landing"
        label: "Homepage Data"
        file: "data/homepage.json"
        fields:
          - { label: "Profile Picture", name: "profile_pic", widget: "image" }
          - { label: "Main Headline", name: "headline", widget: "string" }
          - { label: "Sub Heading", name: "subheading", widget: "string" }
          - { label: "About Me Text", name: "about_text", widget: "text" }
          
  - name: "portfolio"
    label: "My Portfolio Works"
    folder: "data/works"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Work Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "select", options: ["Social Media", "Thumbnails", "Posters", "Memes", "Branding"] }
